@startuml
hide circle
skinparam classAttributeIconSize 0

Class "{abstract}\nCommand" as Command {
  +execute(Model): CommandResult
}
Class ReminderCommand {
  +COMMAND_WORD: String
  +MESSAGE_SUCCESS: String
  +execute(Model): CommandResult
}
Class Model
Class Application
Class Deadline

ReminderCommand -up-|> Command

ReminderCommand ..> Deadline
ReminderCommand ..> Application
@enduml
