@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start
:User enters deadline command;
:Parse index and deadline;

if () then ([valid command])
  :Find target application;
  if () then ([index in range])
    :Update deadline;
    :Commit application state;
    :Show success message;
  else ([index out of range])
    :Show invalid index error;
  endif
else ([invalid command])
  :Show format error;
endif

stop
@enduml
